[versions]
scan-engine = "2.0.2"
kotlin = "2.2.0"
agp = "8.11.1"
compose = "1.8.1"
atomicfu = "0.28.0"

camera-core = "1.5.0"
camera-extensions = "1.5.0"
camera-lifecycle = "1.5.0"
camera-view = "1.5.0"

mlKit = "17.3.0"
playServicesMlkit = "18.3.1"

kotlinCoroutines = "1.10.2"
lifecycleRuntimeKtx = "2.9.1"
activityCompose = "1.10.1"

spotless = "7.1.0"
mokkery = "2.9.0"

uiTestJunit4 = "1.8.3"
robolectric = "4.15"
androidx-test = "1.6.1"
maven-publish = "0.34.0"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidx-test" }

camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camera-core" }
camera-core = { module = "androidx.camera:camera-core", version.ref = "camera-core" }
camera-extensions = { module = "androidx.camera:camera-extensions", version.ref = "camera-extensions" }
camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camera-lifecycle" }
camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "camera-view" }

androidx-lifecycle-runtimeCompose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycleRuntimeKtx" }
kotlin-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlin-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }

google-mlkit = { group = "com.google.mlkit", name = "barcode-scanning", version.ref = "mlKit" }
google-play-services-mlkit = { group = "com.google.android.gms", name = "play-services-mlkit-barcode-scanning", version.ref = "playServicesMlkit" }

# Android testing
androidx-ui-test-junit4-android = { group = "androidx.compose.ui", name = "ui-test-junit4-android", version.ref = "uiTestJunit4" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }

[plugins]
android_library = { id = "com.android.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
androidKotlinMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
atomicfu = { id = "org.jetbrains.kotlinx.atomicfu", version.ref = "atomicfu" }
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
mokkery = { id = "dev.mokkery", version.ref = "mokkery" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }

[bundles]
core = [
    "kotlin-coroutines"
]
camera = [
    "camera-core",
    "camera-camera2",
    "camera-extensions",
    "camera-lifecycle",
    "camera-view"
]
mlkit = [
    "google-mlkit",
    "google-play-services-mlkit",
]